name: Build and test artifacts
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: ./scripts/ci/run-prettier-check.sh
  run-henkilo-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: ./scripts/ci/run-henkilo-ui-tests.sh
  run-oppijanumerorekisteri-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-oppijanumerorekisteri-tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}