name: Build and test artifacts
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-code-format-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ./scripts/ci/run-code-format-checks.sh
  run-henkilo-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ./scripts/ci/run-henkilo-ui-tests.sh
  run-oppijanumerorekisteri-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-oppijanumerorekisteri-tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}