name: Build and test artifacts
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - run: ./scripts/ci/run-code-format-checks.sh
  run-henkilo-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - run: ./scripts/ci/run-henkilo-ui-tests.sh
  run-oppijanumerorekisteri-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-oppijanumerorekisteri-tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}